spring.application.name=firstProject

# MySQL bağlantı adresi ve kimlik bilgileri
spring.datasource.url=jdbc:mysql://localhost:3306/firstproject_db
spring.datasource.username=root
spring.datasource.password=

# Sihirli ayar: Tabloları bizim yerimize otomatik oluştur veya güncelle
spring.jpa.hibernate.ddl-auto=update

# Arka planda çalıştırdığı SQL kodlarını konsolda görebilmemiz için
spring.jpa.show-sql=true

springdoc.override-with-generic-response=false
